apiVersion: v1
kind: Service
metadata:
  name: serverless-redis
  labels:
    app: serverless-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: serverless-redis
